# Generated by Django 5.2 on 2025-06-21 14:29

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('destaque_rodape', models.BooleanField(default=False, verbose_name='Destacar no Rodapé?')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Valor Fixo (R$)')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('validade', models.DateTimeField()),
                ('uso_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo do pedido para uso do cupom (opcional)', max_digits=10, null=True)),
                ('uso_maximo', models.PositiveIntegerField(blank=True, help_text='Máximo de usos globais (opcional)', null=True)),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField()),
                ('descricao_curta', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_antigo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parcelas', models.IntegerField(default=12)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/capas/')),
                ('amostra', models.FileField(blank=True, null=True, upload_to='produtos/amostras/')),
                ('arquivo_produto', models.FileField(blank=True, null=True, upload_to='produtos/completos/', verbose_name='Arquivo do Produto Completo')),
                ('tipo', models.CharField(choices=[('resumo', 'Resumo'), ('combo', 'Combo'), ('flashcard', 'Flashcard'), ('mapas', 'Mapas'), ('recurso', 'Recurso')], default='resumo', max_length=20)),
                ('concurso', models.CharField(max_length=20)),
                ('tag', models.CharField(choices=[('Regular', 'Regular'), ('Pós-Edital', 'Pós-Edital'), ('Pré-Edital', 'Pré-Edital'), ('Curso', 'Curso'), ('Destaque', 'Destaque'), ('Novidade', 'Novidade')], default='Regular', max_length=20)),
                ('is_combo', models.BooleanField(default=False)),
                ('destaque', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True, verbose_name='Produto Ativo?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='produtos', to='produtos.categoria')),
                ('produtos_inclusos', models.ManyToManyField(blank=True, related_name='incluindo_em', to='produtos.produto')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DetalhesProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('materiais_inclusos', models.TextField(blank=True, null=True)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('publico_alvo', models.TextField(blank=True, null=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Detalhes do Produto',
                'verbose_name_plural': 'Detalhes dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='CupomUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usado_em', models.DateTimeField(auto_now_add=True)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.cupom')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupom Usado',
                'verbose_name_plural': 'Cupons Usados',
                'unique_together': {('cupom', 'usuario')},
            },
        ),
    ]
