# Generated by Django 5.2 on 2025-07-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='produtos_elegiveis',
            field=models.ManyToManyField(blank=True, help_text='Deixe em branco para que o cupom seja aplicável a qualquer produto. Selecione um ou mais produtos para restringir o uso do cupom apenas a eles.', to='produtos.produto', verbose_name='Produtos Elegíveis'),
        ),
    ]
