# Generated by Django 5.2 on 2025-07-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_cupom_produtos_elegiveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
