# Generated by Django 5.2 on 2025-06-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_preco_antigo_produto_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Valor Fixo (R$)')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('validade', models.DateTimeField()),
                ('uso_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo do pedido para uso do cupom (opcional)', max_digits=10, null=True)),
            ],
        ),
    ]
