# Generated by Django 5.2 on 2025-06-02 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_cupom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupom',
            options={'verbose_name': 'Cupom', 'verbose_name_plural': 'Cupons'},
        ),
        migrations.AddField(
            model_name='cupom',
            name='uso_maximo',
            field=models.PositiveIntegerField(blank=True, help_text='Máximo de usos globais (opcional)', null=True),
        ),
        migrations.CreateModel(
            name='CupomUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usado_em', models.DateTimeField(auto_now_add=True)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.cupom')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupom Usado',
                'verbose_name_plural': 'Cupons Usados',
                'unique_together': {('cupom', 'usuario')},
            },
        ),
    ]
