# Generated by Django 5.2 on 2025-06-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_cupom_options_cupom_uso_maximo_cupomusado'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='concurso',
            field=models.CharField(default='SEE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='produtos_inclusos',
            field=models.ManyToManyField(blank=True, related_name='incluido_em', to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('ED', 'Educação'), ('JUR', 'Jurídico'), ('ADM', 'Administrativo'), ('TEC', 'Técnico'), ('FISC', 'Fiscal'), ('CON', 'Controle'), ('TI', 'Tecnologia da Informação')], max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
