# Generated by Django 5.2 on 2025-06-03 00:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produtos_inclusos',
            field=models.ManyToManyField(blank=True, related_name='incluindo_em', to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
