# Generated by Django 5.2 on 2025-06-03 00:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_produto_categoria_alter_produto_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=16, null=True),
        ),
    ]
