# Generated by Django 5.2 on 2025-06-03 00:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=16, unique=True),
        ),
    ]
