# Generated by Django 5.2 on 2025-06-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_produto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='sigla',
            field=models.CharField(default='SEE', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
    ]
