# Generated by Django 5.2 on 2025-06-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_categoria_sigla_alter_produto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('resumo', 'Resumo'), ('combo', 'Combo'), ('flashcard', 'Flashcard'), ('mapas', 'Mapas'), ('recurso', 'Recurso')], default='resumo', max_length=20),
        ),
    ]
