# Generated by Django 5.2 on 2025-06-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='amostra',
            field=models.FileField(blank=True, null=True, upload_to='amostras/'),
        ),
    ]
