# Generated by Django 5.2 on 2025-06-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_produto_amostra'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='arquivo_produto',
            field=models.FileField(blank=True, null=True, upload_to='produtos/completos/', verbose_name='Arquivo do Produto Completo'),
        ),
    ]
