# Generated by Django 5.2 on 2025-06-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_produto_arquivo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='amostra',
            field=models.FileField(blank=True, null=True, upload_to='produtos/amostras/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/capas/'),
        ),
    ]
