# Generated by Django 5.2 on 2025-06-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_alter_produto_amostra_alter_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='produtos.categoria'),
        ),
    ]
