# Generated by Django 5.2 on 2025-06-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_remove_produto_categoria_produto_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Produto Ativo?'),
        ),
    ]
