# Generated by Django 5.2 on 2025-06-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_produto_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='destaque_rodape',
            field=models.BooleanField(default=False, verbose_name='Destacar no Rodapé?'),
        ),
    ]
