# Generated by Django 5.2 on 2025-06-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
