# Generated by Django 5.2 on 2025-06-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_referencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='referencia',
            new_name='codigo',
        ),
    ]
