# Generated by Django 5.2 on 2025-06-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_rename_referencia_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('falhou', 'Falhou'), ('reembolso', 'Reembolso')], default='pendente', max_length=10),
        ),
    ]
