# Generated by Django 5.2 on 2025-06-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagarme_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Pagar.me'),
        ),
    ]
