# Generated by Django 5.2 on 2025-06-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_pagarme_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pagarme_id',
        ),
    ]
