# Generated by Django 5.2 on 2025-06-21 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Área de Interesse',
                'verbose_name_plural': 'Áreas de Interesse',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_method', models.CharField(blank=True, choices=[('site', 'Site'), ('google', 'Google')], max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Telefone')),
                ('formacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Formação Acadêmica')),
                ('concurso_desejado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Concurso Desejado')),
                ('aprovacoes', models.TextField(blank=True, null=True, verbose_name='Aprovações Anteriores')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Sobre Mim')),
                ('areas_interesse', models.ManyToManyField(blank=True, related_name='perfis', to='accounts.areainteresse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
