# Generated by Django 5.2 on 2025-06-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='signup_method',
            field=models.CharField(choices=[('site', 'Site'), ('google', 'Google')], default='site', max_length=20),
        ),
    ]
