# Generated by Django 5.2 on 2025-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_signup_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='signup_method',
            field=models.CharField(blank=True, choices=[('site', 'Site'), ('google', 'Google')], max_length=20, null=True),
        ),
    ]
