# Generated by Django 5.2 on 2025-06-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_signup_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aprovacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Aprovações Anteriores'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre Mim'),
        ),
        migrations.AddField(
            model_name='profile',
            name='concurso_desejado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Concurso Desejado'),
        ),
        migrations.AddField(
            model_name='profile',
            name='formacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formação Acadêmica'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Telefone'),
        ),
    ]
