# Generated by Django 5.2 on 2025-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_aprovacoes_profile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='areas_interesse',
            field=models.ManyToManyField(blank=True, related_name='perfis', to='accounts.areainteresse'),
        ),
    ]
