# Generated by Django 5.2 on 2025-06-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_areainteresse_profile_areas_interesse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areainteresse',
            options={'verbose_name': 'Área de Interesse', 'verbose_name_plural': 'Áreas de Interesse'},
        ),
    ]
