# Generated by Django 5.2 on 2025-06-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprovado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='aprovados/')),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
