# Generated by Django 5.2 on 2025-07-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprovados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprovado',
            name='link_externo',
            field=models.URLField(blank=True, help_text='Link do Instagram, LinkedIn ou outra página do aprovado.', max_length=255, null=True, verbose_name='Link Externo (Opcional)'),
        ),
    ]
